// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIidacqqoYCkaGXm7M20pnUm-uQoDERFk',
    appId: '1:251036577954:web:62b3eecba9c62bf9a027fb',
    messagingSenderId: '251036577954',
    projectId: 'iambulance-eea13',
    authDomain: 'iambulance-eea13.firebaseapp.com',
    storageBucket: 'iambulance-eea13.appspot.com',
    measurementId: 'G-R633TMXPGM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBm2kRSx_CsFA1BhvcU8Is6sU5YxUcLwbI',
    appId: '1:392841827787:android:8e6c6c81f6c2540ca4924e',
    messagingSenderId: '392841827787',
    projectId: 'health-care-app-791f6',
    storageBucket: 'health-care-app-791f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUyMKOlq0tT_MrtHALyvtE1r9OWLPnzmE',
    appId: '1:251036577954:ios:1eea77fa182d7274a027fb',
    messagingSenderId: '251036577954',
    projectId: 'iambulance-eea13',
    storageBucket: 'iambulance-eea13.appspot.com',
    iosClientId: '251036577954-gd657hrtu8dprku3b22abojnptfh683j.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthCareDriver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUyMKOlq0tT_MrtHALyvtE1r9OWLPnzmE',
    appId: '1:251036577954:ios:521ab56a6d7a4793a027fb',
    messagingSenderId: '251036577954',
    projectId: 'iambulance-eea13',
    storageBucket: 'iambulance-eea13.appspot.com',
    iosClientId: '251036577954-ufcibdfimk3rag3lf50rh5h9cc3smeu1.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthCareDriver.RunnerTests',
  );
}
